---
- name: firewalld open tcp 80 port
  become: yes
  become_user: root
  firewalld:
    immediate: true
    permanent: true
    service: http
    state: enabled

- name: Put h2o.conf
  become: yes
  become_user: root
  copy:
    src: portal-h2o.conf
    dest: /etc/h2o/portal-h2o.conf

- name: Remove h2o.conf
  become: yes
  become_user: root
  file:
    state: absent
    path: /etc/h2o/h2o.conf

- name: Put h2o.conf link
  become: yes
  become_user: root
  file:
    state: link
    src: "/etc/h2o/portal-h2o.conf"
    dest: /etc/h2o/h2o.conf

- name: Put torb.portal.service
  become: yes
  become_user: root
  copy:
    src: torb.portal.service
    dest: /etc/systemd/system/torb.portal.service

- name: Install for portal
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb/portal
  shell: |
    bash -lc "carton install"
