---
- name: Restart mariadb
  become: yes
  become_user: root
  systemd:
    name: mariadb
    state: restarted
    daemon_reload: yes

- name: Run db/init.sh
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb
  command: |
    db/init.sh
